version: 0.2

phases:
  install: 
    runtime-versions:
      java: latest
    commands:
      - yum install -y maven
      - yum install java-1.8.0-openjdk-devel.x86_64 -y
      - yum install zip -y
  build:
    commands:
      - mvn clean install
artifacts:
  files:
    - target/accessing-data-mysql-complete-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - beforeinstall.sh
    - applicationstart.sh
  discard-paths: yes
